### PR TITLE
Include modules necessary for either controller or integration tests.

### PR DESCRIPTION
**Pull request by tgxworld**

### CODE REVIEW

**Comment by tgxworld** [comment]
@kaspth I tried out `ActiveSupport.on_load` but it didn't work for some reason even though the ancestors looked the same.

**Comment by kaspth** [comment]
Did you require everything you had to? :smile:
There also might be issues if you didn't `extend ActiveSupport::Concern`.

**Comment by tgxworld** [comment]
I tried something like this

``` ruby
require 'rails/controller/testing/test_process'
require 'rails/controller/testing/integration'
require 'rails/controller/testing/template_assertions'

ActiveSupport.on_load(:action_controller) do
  ActionController::TestCase.include Rails::Controller::Testing::TemplateAssertions
  ActionController::TestCase.include Rails::Controller::Testing::TestProcess
end

ActiveSupport.on_load(:action_controller) do
  ActionDispatch::IntegrationTest.include Rails::Controller::Testing::TemplateAssertions
  ActionDispatch::IntegrationTest.include Rails::Controller::Testing::Integration
end
```

Not sure if I'm missing out on anything xD

**Comment by kaspth** [comment]
Doesn't `ActionDispatch::IntegrationTest` inherit from `ActionController::TestCase`?

Also within `on_load(:action_controller)` you're within the `ActionController` namespace, so `TestCase` will refer back to `ActionController::TestCase`.

If that doesn't work, then I'm drawing a blank. @rafaelfranca can you c/d?

**Comment by tgxworld** [comment]
> Doesn't ActionDispatch::IntegrationTest inherit from ActionController::TestCase?

Noped, both of them inherits direction from `ActiveSupport::TestCase`.

> Also within on_load(:action_controller) you're within the ActionController namespace, so TestCase will refer back to ActionController::TestCase.

Ah you're right :)

**Comment by kaspth** [comment]
Okay, then we should use something like `on_load(:action_dispatch)`

**Comment by tgxworld** [comment]
Rails doesn't run any load hooks for `action_dispatch` though.

**Comment by kaspth** [comment]
Hm, you're right. I guess we can assume it's loaded when Action Controller is.

**Comment by tgxworld** [comment]
@kaspth Thanks for helping :smile:

**Comment by kaspth** [comment]
@tgxworld happy to help :+1:

**Comment by rafaelfranca** [comment]
:+1:

**Comment by tgxworld** [comment]
Thanks @rafaelfranca  :smile:

**Pull request merged**
