### PR TITLE
Update gemspec.

### PR DESCRIPTION
**Pull request by tgxworld**

### CODE REVIEW

**Comment by tgxworld** [comment]
@rafaelfranca Are you publishing a new gem? Otherwise I can do it :)

**Comment by rafaelfranca** [comment]
Please do it.

**Comment by tgxworld** [comment]
@rafaelfranca will do.

**Comment by rafaelfranca** [comment]
@tgxworld could you add me to rubygem? Seems we don't have access to it.

```
gem owner -a rafaelmfranca@gmail.com rails-controller-testing
```

**Comment by tgxworld** [comment]
@rafaelfranca done :)

**Pull request merged**
