### PR TITLE
Fix the gem name in README.

### PR DESCRIPTION
**Pull request by kaspth**

### CODE REVIEW

**Comment by tgxworld** [comment]
Thank @kaspth!!

**Comment by tgxworld** [comment]
@kaspth Btw would you mind helping me review this plugin? It is my first time making one so I'm not sure if I've done anything wrong.  I mainly referred to `rails-dom-testing` :) Thanks in advance!

**Comment by kaspth** [comment]
Sure:
- You'd want to add `*.gem` to `.gitignore`.
- `assigns()` is just `assigns`
- You should add `.travis.yml`, look in rails-dom-testing for help
- Rails version should probably be `'>= 4.2'`, instead of: https://github.com/tgxworld/rails-controller-testing/blob/master/rails-controller-testing.gemspec#L20
- Use a Railtie here instead: https://github.com/tgxworld/rails-controller-testing/blob/master/lib/rails-controller-testing.rb#L21
  
  ``` ruby
  ActiveSupport.on_load(:action_controller) do # We want it in ActionController::TestCase not ActiveSupport::TestCase
   TestCase.include Rails::Controller::Testing
  end
  ```

cc @rafaelfranca

**Comment by tgxworld** [comment]
@kaspth Thanks for reviewing :smile: I'll work on the changes soon!

**Pull request merged**
